VAR/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using VAR.Models;
using VAR.Repositries;
using Microsoft.AspNetCore.Authorization;

namespace VAR.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly IAdminRepo adminRepo;

        public AdminController(IAdminRepo adminRepo)
        {
            this.adminRepo = adminRepo;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> getAllAdmins()
        {
            List<Admin> admins= await adminRepo.getAll();
            return View(admins);
        }
        public async Task<IActionResult> getAdminById(int id)
        {
            Admin? admin = await adminRepo.getById(id);
            //Order order = new Order();
            //ViewBag.order = order;
            if (admin != null) return View(admin);
            else return View("Error");
        }

        [HttpGet]
        public IActionResult addAdmin()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> addAdmin(Admin adminToAdd)
        {
            if (ModelState.IsValid)
            {
                Admin? admin = await adminRepo.add(adminToAdd);
                return RedirectToAction("getAllAdmins");
            }
            return View();

        }

        public async Task<IActionResult> Edit(int id)
        {
            Admin? admin = await adminRepo.getById(id);
            if (admin == null)
            {
                return NotFound();
            }
            return View(admin);
        }
        [HttpPost]
        public async Task<IActionResult> Update(Admin admin)
        {
            if (ModelState.IsValid)
            {
                await adminRepo.edit(admin);
                return RedirectToAction("getAllAdmins");
            }
            return View("Edit",admin);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await adminRepo.delete(id);
            return RedirectToAction("getAllAdmins");
        }

    }
}

VAR/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VAR.Models;
using VAR.Repositries;

namespace VAR.Controllers
{
    public class ItemController : Controller
    {
        private readonly IItemRepo itemRepo;

        public ItemController(IItemRepo itemRepo)
        {
            this.itemRepo = itemRepo;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> getAllItems()
        {
            List<Item>? items = await itemRepo.getAll();     
            return View(items);
        }
        public async Task<IActionResult> getAllItemsInStock()
        {
           List<Item>? items =  await itemRepo.getAllInStock();

           ViewBag.Items = new SelectList(items, "Id", "Name");
           return PartialView("_getAllItemsInStock",items);
        }

        //public async Task<IActionResult> itemCart(int )
        //{

        //    return PartialView("_itemsCart");
        //}

        [HttpGet]
        public IActionResult AddItem()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddItem(Item itemToAdd)
        {
            if (ModelState.IsValid)
            {
                Item? item = await itemRepo.Add(itemToAdd);
                return RedirectToAction("getAllItems");
            }
            return View();

        }
        public void UpdateItemStock(int id, int newInStock)
        {
            itemRepo.UpdateItemStock(id, newInStock);
          
        }

        public async Task<IActionResult> Edit(int id)
        {
            Item? item = await itemRepo.getById(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }
        [HttpPost]
        public async Task<IActionResult> Update(Item item)
        {
            if (ModelState.IsValid)
            {
                await itemRepo.edit(item);
                return RedirectToAction("getAllItems");
            }
            return View(item);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {          
                await itemRepo.delete(id);
                return RedirectToAction("getAllItems");
        }
        public IActionResult itemCart()
        {

            return PartialView("_itemsCart");
        }
    }
}

VAR/Controllers/OrderItemDetailsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VAR.Models;
using VAR.Repositries;
using VAR.ViewModels;

namespace VAR.Controllers
{
    public class OrderItemDetailsController : Controller
    {
        private readonly IOrderItemDetailsRepo orderItemDetailsRepo;

        public OrderItemDetailsController(IOrderItemDetailsRepo orderItemDetailsRepo)
        {
            this.orderItemDetailsRepo = orderItemDetailsRepo;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Add()
        {          
         return View();
                               
        }
        [HttpPost]
        public async Task<IActionResult> Add([FromBody] OrderItemDetails orderItemDetailsToAdd)
        {
            if (ModelState.IsValid)
            {
                OrderItemDetails? orderItemDetails = await orderItemDetailsRepo.Add(orderItemDetailsToAdd);
                return Json(orderItemDetailsToAdd);
                
            }
            return View("Error");

        }
        [HttpPost]
        public async Task<IActionResult> AddJustItemsOrder([FromForm] OrderItemDetails orderItemDetailsToAdd)
        {
            if (ModelState.IsValid)
            {
                OrderItemDetails? orderItemDetails = await orderItemDetailsRepo.Add(orderItemDetailsToAdd);
                return Json(orderItemDetailsToAdd);

            }
            return View("Error");

        }
    }
}

VAR/Views/Shared/_AddOrder.cshtml
@model Order

<form asp-action="AddOrderDB" asp-controller="Order" method="post">
    <input hidden asp-for="StartTime"  />

    <input hidden asp-for="EndTime" />

    <input hidden asp-for="adminID" />

    <input hidden asp-for="playstationID" />

    <button hidden id="submit-order" type="submit">Add</button>
</form>

VAR/Views/Shared/_AdimnLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>V A R - Admin</title>

    <!-- Custom fonts for this template-->
    <link href="~/AdminDashboard/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

    <!-- Custom styles for this template-->
    <link href="~/AdminDashboard/css/sb-admin-2.min.css" rel="stylesheet">

     <!-- Custom styles for this page -->
    <link href="~/AdminDashboard/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i ><i class="fa-solid fa-gamepad" style="color: #ffffff;"></i></i>
                </div>
                <div class="sidebar-brand-text mx-3">Var</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item mt-5">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fa-regular fa-file-lines"></i>
                    <span>Orders</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <!-- <h6 class="collapse-header">Custom Utilities:</h6> -->
                        <a class="collapse-item" asp-action="GetOrdersPagination" asp-controller="Order">Show Orders</a>
                    </div>
                </div>
            </li>

             <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                   <i class="fa-solid fa-house-flag"></i>
                    <span>Rooms</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                      <!-- <h6 class="collapse-header">Custom Utilities:</h6> -->  
                        <a class="collapse-item" asp-action="getAllRoomsForAdmin" asp-controller="PlaystationRoom" >Show Rooms</a>
                        <a class="collapse-item" asp-action="AddPlaystationRoom" asp-controller="PlaystationRoom">Add Room</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                   aria-expanded="true" aria-controls="collapsePages">
                    <i class="fa-solid fa-mug-hot"></i>
                    <span>Cafe</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                      <!-- <h6 class="collapse-header">Custom Utilities:</h6> -->  
                        <a class="collapse-item" asp-action="getAllItems" asp-controller="Item">Show All Items</a>
                        <a class="collapse-item" asp-action="AddItem" asp-controller="Item">Add New Item</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Charts -->
             <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAdmin"
                   aria-expanded="true" aria-controls="collapsePages">
                    <i class="fa-solid fa-address-card"></i>
                    <span>Admins And Employees</span>
                </a>
                <div id="collapseAdmin" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                      <!-- <h6 class="collapse-header">Custom Utilities:</h6> -->  
                        <a class="collapse-item" asp-action="getAllAdmins" asp-controller="Admin">Show All</a>
                        <a class="collapse-item" asp-action="addAdmin" asp-controller="Admin">Add New Employee</a>
                    </div>
                </div>
            </li>

           
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">  
                              <!-- Nav Item - User Information -->
                     @*   <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span id="user-name" class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>*@
                              @*  <img class="img-profile rounded-circle"
                                     src="AdminDashboard/img/undraw_profile.svg">*@
                           @* </a>*@
                            <!-- Dropdown - User Information -->
                           @* <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>
                      *@
                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Render Body-->
                
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <div class="container">
                    @RenderBody()
                </div>
                  
                
                <!-- /.container-fluid -->

            </div>

            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
    <script src="~/AdminDashboard/vendor/jquery/jquery.min.js"></script>
    <script src="~/AdminDashboard/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/AdminDashboard/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/AdminDashboard/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    @*<script src="~/AdminDashboard/vendor/chart.js/Chart.min.js"></script>*@

    <!-- Page level custom scripts -->
    <script src="~/AdminDashboard/js/demo/chart-area-demo.js"></script>
    <script src="~/AdminDashboard/js/demo/chart-pie-demo.js"></script>

     @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

VAR/Views/Shared/_InvoiceModal.cshtml
<div class="row justify-content-center mt-5">
    <!-- Button trigger modal -->
    <button type="button" onclick="showOrder()" class="col-2 order-btn btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        Display Invoice
    </button>
</div>


<!-- Modal -->
<div class="modal fade  modal-lg" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-body">
                <div class="input-group mb-3">
                    <label for="discount">Add Discount</label>
                    <input id="discount" type="number" class="form-control" placeholder="" min="0" step="0.5" value="0">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="confirm-order" onclick="confirmOrder()" type="button" class="btn btn-primary">Order</button>
            </div>
        </div>
    </div>
</div>

VAR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VAR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VAR.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)

</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VAR/Views/Shared/_Spinner.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="spinner-border text-success" role="status">
    <span class="visually-hidden">Loading...</span>
</div>

VAR/Views/Shared/_VarLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>V A R</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/assets/img/Yassin/ps5-controller-fav1.png" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <link href="~/css/toastr.css" rel="stylesheet" />
    @*<link href="~/css/toastr.min.css" rel="stylesheet" /> *@
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
        @*<link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />*@

     @await RenderSectionAsync("Styles", required: false)

</head>
<body id="page-top">
    <input id="admin-id" hidden value="" />
   
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="#page-top"><img src="~/assets/img/Yassin/navbar-logo.png" alt="..." /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars ms-1"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul id="nav-ul" class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link" asp-action="getAllRooms" asp-controller="PlaystationRoom">Rooms</a></li>
                    <li class="nav-item"><a class="nav-link" asp-action="Add" asp-controller="OrderItemDetails">CAFÉ</a></li>
                    @*<li class="nav-item"><a class="nav-link" target="_blank" asp-action="GetOrdersPagination" asp-controller="Order">Admin</a></li>*@
                    <li class="nav-item"><a class="nav-link"  asp-action="LogOut" asp-controller="Account">Log Out</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <script>
        function getCookie(cookieNam) {
            // Get the value of the myCookie cookie
            const cookieValue = document.cookie.split('; ').find(cookie => cookie.startsWith(cookieNam)).split('=')[1];

            // Parse the value as JSON
            const parsedValue = JSON.parse(decodeURIComponent(cookieValue));
            return parsedValue;
        }
        var adminId = getCookie("AdminId");
        if (adminId == 1 || adminId == 2) {
            var htmlCode = '<li class="nav-item"><a class="nav-link" target="_blank" href="/Order/GetOrdersPagination" >Admin</a></li>';
            var ulDiv = document.getElementById('nav-ul');
            ulDiv.innerHTML += htmlCode;

        }
        //adminIdInput.value = adminId;

    </script>
    <!-- Services-->
    <section class="page-section" id="services">
        <div class="container">
            @RenderBody()
        </div>   
    </section>
   
    <!-- Footer-->
    <footer class="footer py-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-start">Copyright &copy; Ahmed Nouh 2023</div>
                <div class="col-lg-4 my-3 my-lg-0">
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <div class="col-lg-4 text-lg-end">
                    <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                    <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
                </div>
            </div>
        </div>
    </footer>
    
    <!-- Bootstrap core JS-->
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>*@

        <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <!-- Core theme JS-->
        <script src="~/js/toastr.js"></script>
    <script src="~/js/scripts.js"></script>

    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

 @await RenderSectionAsync("Scripts", required: false)

    @*<script src="~/js/toastr.min.js"></script>  *@
</body>
</html>

VAR/Views/Shared/_getAllItemsInStock.cshtml
@model List<Item>

<div class="col-6 d-flex text-center mb-4 mt-3">
    <label class="me-1" for="select-item" style="padding-top: 5px;">Items</label>
    <select class="form-control " id="select-item" onchange="setItemNumInStock()" asp-items="ViewBag.Items">
        <option value="">Choose One</option>
    </select>
 </div>


<div class="col-6 d-flex amount text-center mb-3 mt-3">
    <label class="me-1" for="number" style="padding-top: 5px;">Amount</label>
   <input id="number" class=" form-control w-100" type="number" value="1"  />
 </div>

<div id="add-div">
    <button class="btn btn-primary" id="add">Add</button>
</div>

<script>
    var itemList = @Html.Raw(Json.Serialize(Model));
   
</script>

<script src="/js/Item.js"></script>

VAR/Views/Shared/_itemsCart.cshtml
@model Item
<div>
    <table class="table" id="order-table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    Quantity
                </th>
                <th>
                    Total Price
                </th>
            </tr>
        </thead>
        <tbody id="table-body"></tbody>    
    </table>
</div>

VAR/Views/Shared/_orderModal.cshtml
    <h2 class="fs-5">Popover in a modal</h2>
    <p>This <button class="btn btn-secondary" data-bs-toggle="popover" title="Popover title" data-bs-content="Popover body content is set in this attribute.">button</button> triggers a popover on click.</p>
    <hr>
    <h2 class="fs-5">Tooltips in a modal</h2>
    <p><a href="#" data-bs-toggle="tooltip" title="Tooltip">This link</a> and <a href="#" data-bs-toggle="tooltip" title="Tooltip">that link</a> have tooltips on hover.</p>